spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zvp2jt6ccu6lj7zy:svrkhh4kcczc0efo@nr84dudlpkazpylz.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/pjcd3z1g0e8cpjzp
    username: zvp2jt6ccu6lj7zy
    password: svrkhh4kcczc0efo
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true